"""Regenerated markdown projections under views/ — observable, never canonical.

Every writer here is best-effort: view rendering can never break a synopsis
rebuild, a capture's KG pass, or a timeline roll.
"""
from __future__ import annotations

import logging
from pathlib import Path

from br8n.vault import files, layout

logger = logging.getLogger(__name__)

BANNER = "> [!note] derived view — regenerated by br8n; edits here won't stick\n\n"


def _view_path(*segments: str):
    return layout.vault_root() / layout.VIEWS_DIRNAME / "/".join(segments)


def _pair_view_path(kind: str, project: str, kb: str):
    """views/<kind>/<project>/<kb>.md — a directory per project so two
    pairs can't flatten onto one filename ('a-b'/'c' vs 'a'/'b-c')."""
    return _view_path(kind, layout.safe_segment(project),
                      f"{layout.safe_segment(kb)}.md")


def write_synopsis_view(store, kb_id: str, content: list[dict]) -> None:
    try:
        project, kb = store._kb_names(kb_id)
        lines = [BANNER, f"# Synopsis — {project}/{kb}\n"]
        for entry in content or []:
            if isinstance(entry, dict):
                first = True
                for k, v in entry.items():
                    prefix = "- **" + str(k) + ":** " if first else "  - " + str(k) + ": "
                    lines.append(f"{prefix}{v}\n")
                    first = False
            else:
                lines.append(f"- {entry}\n")
        files.atomic_write(_pair_view_path("synopsis", project, kb), "".join(lines))
    except Exception:  # noqa: BLE001
        logger.debug("synopsis view skipped", exc_info=True)


def write_activity_view(store, kb_id: str) -> None:
    """Node rollup with wikilinks into grounding snapshots (graph view fuel)."""
    try:
        project, kb = store._kb_names(kb_id)
        stats = store.kg_stats(kb_id)
        nodes = store.list_kg_nodes(kb_id, limit=50)
        lines = [BANNER, f"# Activity — {project}/{kb}\n",
                 f"\n{stats['node_count']} nodes · {stats['edge_count']} edges\n\n"]
        for n in nodes:
            links = []
            for fid in (n.get("grounded_in") or [])[-3:]:
                p = store.vault_path_for(fid)
                if p:
                    links.append(f"[[{Path(p).stem}]]")
            suffix = f" — {' '.join(links)}" if links else ""
            lines.append(f"- **{n['type']}** {n['label']}{suffix}\n")
        files.atomic_write(_pair_view_path("activity", project, kb), "".join(lines))
    except Exception:  # noqa: BLE001
        logger.debug("activity view skipped", exc_info=True)


def mirror_timeline(project: str, kb: str, recent_text: str, week_text: str) -> None:
    try:
        d = _view_path("timeline", f"{layout.safe_segment(project)}-{layout.safe_segment(kb)}")
        files.atomic_write(d / "recent.md", BANNER + recent_text)
        files.atomic_write(d / "week.md", BANNER + week_text)
    except Exception:  # noqa: BLE001
        logger.debug("timeline mirror skipped", exc_info=True)
